In [23]:
import pandas as pd
import numpy as np
import matplotlib as plt
import copy, math

std_data = pd.read_csv('Student_Performance.csv')
std_data.columns = std_data.columns.str.replace(' ', '_')
std_data
#print(type(std_data))
#print(std_data.info())

Hours_Studied  Previous_Scores Extracurricular_Activities  Sleep_Hours  \
0                 7               99                        Yes            9   
1                 4               82                         No            4   
2                 8               51                        Yes            7   
3                 5               52                        Yes            5   
4                 7               75                         No            8   
...             ...              ...                        ...          ...   
9995              1               49                        Yes            4   
9996              7               64                        Yes            8   
9997              6               83                        Yes            8   
9998              9               97                        Yes            7   
9999              7               74                         No            8   

      Sample_Question_Papers_Practiced  Performance_Index  
0                                    1               91.0  
1                                    2               65.0  
2                                    2               45.0  
3                                    2               36.0  
4                                    5               66.0  
...                                ...                ...  
9995                                 2               23.0  
9996                                 5               58.0  
9997                                 5               74.0  
9998                                 0               95.0  
9999                                 1               64.0  

[10000 rows x 6 columns]

In [24]:
#std_data.rename(columns={'Extracurricular Activities' : 'Extracurricular'}, inplace = True)
#std_data
std_data = std_data.replace('Yes', '1', regex = True)
std_data = std_data.replace('No', '0', regex = True)
std_data['Extracurricular_Activities'] = std_data['Extracurricular_Activities'].astype('int64')
std_data

Hours_Studied  Previous_Scores  Extracurricular_Activities  Sleep_Hours  \
0                 7               99                           1            9   
1                 4               82                           0            4   
2                 8               51                           1            7   
3                 5               52                           1            5   
4                 7               75                           0            8   
...             ...              ...                         ...          ...   
9995              1               49                           1            4   
9996              7               64                           1            8   
9997              6               83                           1            8   
9998              9               97                           1            7   
9999              7               74                           0            8   

      Sample_Question_Papers_Practiced  Performance_Index  
0                                    1               91.0  
1                                    2               65.0  
2                                    2               45.0  
3                                    2               36.0  
4                                    5               66.0  
...                                ...                ...  
9995                                 2               23.0  
9996                                 5               58.0  
9997                                 5               74.0  
9998                                 0               95.0  
9999                                 1               64.0  

[10000 rows x 6 columns]

In [28]:
number = std_data.shape[0]
print(number)
number_train = int(number * 9 / 10)
for j in range(std_data.shape[1]):
  xj_train = np.zeros(number_train)
  print(xj_train)

10000
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]


In [30]:
for j in range(std_data.shape[1]):
  for i in range(number_train):
    xj_train[i] = std_data.iloc[i, j]
  print(xj_train)

#print(x1_train)

[7. 4. 8. ... 4. 9. 2.]
[99. 82. 51. ... 91. 57. 66.]
[1. 0. 1. ... 0. 0. 0.]
[9. 4. 7. ... 7. 5. 6.]
[1. 2. 2. ... 1. 0. 9.]
[91. 65. 45. ... 77. 51. 43.]
