<a href="https://colab.research.google.com/github/CC-Shivansh-Gupta/logistic-_reg/blob/main/v1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [367]:
import pandas as pd
import numpy as np
import matplotlib as plt
import copy, math

std_data = pd.read_csv('Student_Performance.csv')
std_data.columns = std_data.columns.str.replace(' ', '_')
std_data
#print(type(std_data))
#print(std_data.info())

Hours_Studied  Previous_Scores Extracurricular_Activities  Sleep_Hours  \
0                 7               99                        Yes            9   
1                 4               82                         No            4   
2                 8               51                        Yes            7   
3                 5               52                        Yes            5   
4                 7               75                         No            8   
...             ...              ...                        ...          ...   
9995              1               49                        Yes            4   
9996              7               64                        Yes            8   
9997              6               83                        Yes            8   
9998              9               97                        Yes            7   
9999              7               74                         No            8   

      Sample_Question_Papers_Practiced  Performance_Index  
0                                    1               91.0  
1                                    2               65.0  
2                                    2               45.0  
3                                    2               36.0  
4                                    5               66.0  
...                                ...                ...  
9995                                 2               23.0  
9996                                 5               58.0  
9997                                 5               74.0  
9998                                 0               95.0  
9999                                 1               64.0  

[10000 rows x 6 columns]

In [368]:
#std_data.rename(columns={'Extracurricular Activities' : 'Extracurricular'}, inplace = True)
#std_data
std_data = std_data.replace('Yes', '1', regex = True)
std_data = std_data.replace('No', '0', regex = True)
std_data['Extracurricular_Activities'] = std_data['Extracurricular_Activities'].astype('int64')
std_data

Hours_Studied  Previous_Scores  Extracurricular_Activities  Sleep_Hours  \
0                 7               99                           1            9   
1                 4               82                           0            4   
2                 8               51                           1            7   
3                 5               52                           1            5   
4                 7               75                           0            8   
...             ...              ...                         ...          ...   
9995              1               49                           1            4   
9996              7               64                           1            8   
9997              6               83                           1            8   
9998              9               97                           1            7   
9999              7               74                           0            8   

      Sample_Question_Papers_Practiced  Performance_Index  
0                                    1               91.0  
1                                    2               65.0  
2                                    2               45.0  
3                                    2               36.0  
4                                    5               66.0  
...                                ...                ...  
9995                                 2               23.0  
9996                                 5               58.0  
9997                                 5               74.0  
9998                                 0               95.0  
9999                                 1               64.0  

[10000 rows x 6 columns]

In [369]:
def normalise_data(arr):
  #min_val = np.min(arr)
  #max_val = np.max(arr)
  mean = np.mean(arr)
  std = np.std(arr)
  norm_arr = np.zeros(len(arr))
  for i in range(len(arr)):
    norm_arr[i] = (arr[i] - mean) / std
  return norm_arr


In [370]:
for i in range(std_data.shape[1]-1):
  std_data.iloc[:, i] = normalise_data(std_data.iloc[:, i])
std_data

<ipython-input-370-fae890c2cb34>:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ 0.77518771 -0.38348058  1.16141048 ...  0.38896495  1.54763324
  0.77518771]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  std_data.iloc[:, i] = normalise_data(std_data.iloc[:, i])
<ipython-input-370-fae890c2cb34>:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ 1.70417565  0.72391268 -1.06362569 ...  0.7815752   1.5888506
  0.26261245]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  std_data.iloc[:, i] = normalise_data(std_data.iloc[:, i])
<ipython-input-370-fae890c2cb34>:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ 1.01045465 -0.98965352  1.01045465 ...  1.01045465  1.01045465
 -0.98965352]' has d

Hours_Studied  Previous_Scores  Extracurricular_Activities  Sleep_Hours  \
0          0.775188         1.704176                    1.010455     1.456205   
1         -0.383481         0.723913                   -0.989654    -1.492294   
2          1.161410        -1.063626                    1.010455     0.276805   
3          0.002742        -1.005963                    1.010455    -0.902594   
4          0.775188         0.320275                   -0.989654     0.866505   
...             ...              ...                         ...          ...   
9995      -1.542149        -1.178951                    1.010455    -1.492294   
9996       0.775188        -0.314013                    1.010455     0.866505   
9997       0.388965         0.781575                    1.010455     0.866505   
9998       1.547633         1.588851                    1.010455     0.276805   
9999       0.775188         0.262612                   -0.989654     0.866505   

      Sample_Question_Papers_Practiced  Performance_Index  
0                            -1.249754               91.0  
1                            -0.900982               65.0  
2                            -0.900982               45.0  
3                            -0.900982               36.0  
4                             0.145333               66.0  
...                                ...                ...  
9995                         -0.900982               23.0  
9996                          0.145333               58.0  
9997                          0.145333               74.0  
9998                         -1.598526               95.0  
9999                         -1.249754               64.0  

[10000 rows x 6 columns]

In [371]:
number = std_data.shape[0]
print(number)
number_train = int(number * 9 / 10)


10000


In [372]:
x_train_list = []
for j in range(std_data.shape[1]):
    xj_train = np.zeros(number_train)
    for i in range(number_train):
        xj_train[i] = std_data.iloc[i, j]
    x_train_list.append(xj_train)  # Append xj_train directly to the list

# Separate the features (x_train) from the target (y_train)
x_train_tup = tuple(x_train_list[:-1]) # Exclude the last column (target)
x_train = np.column_stack(x_train_tup)
y_train = x_train_list[-1]  # The last column is the target

print(x_train)
print(y_train)

[[ 0.77518771  1.70417565  1.01045465  1.45620461 -1.24975394]
 [-0.38348058  0.72391268 -0.98965352 -1.49229423 -0.90098215]
 [ 1.16141048 -1.06362569  1.01045465  0.27680507 -0.90098215]
 ...
 [-0.38348058  1.24287543 -0.98965352  0.27680507 -1.24975394]
 [ 1.54763324 -0.71765053 -0.98965352 -0.90259446 -1.59852572]
 [-1.15592611 -0.19868777 -0.98965352 -0.3128947   1.54042034]]
[91. 65. 45. ... 77. 51. 43.]


In [373]:
w_para = np.zeros(std_data.shape[1] - 1)
print(w_para)
b_para = 0
print(b_para)

[0. 0. 0. 0. 0.]
0


In [374]:
def prediction(x, w, b):
  c = np.dot(x, w) + b
  return c

In [375]:
def predict():
  predic= np.zeros(number_train)
  for i in range(number_train):
    predic[i] = prediction(x_train[i], w_para, b_para)
    #print(predic)
  return predic


In [376]:
pred = predict()

In [377]:
def loss_calc(pred, y):
  loss = 1/2*((pred - y) ** 2)
  return loss

In [378]:
def lossss():
  losses = np.zeros(number_train)
  for i in range(number_train):
    losses[i] = loss_calc(pred[i], y_train[i])
  #print(losses)
  return losses

In [379]:
loss = lossss()

In [380]:
def cost_function(loss, l, w):
  costie = np.mean(loss) + (l * np.sum(np.square(w)))/(2*len(loss))
  #print(costie)
  return costie

In [381]:
cost = cost_function(loss, 1, w_para)

In [382]:
def grad_desc(w, b, cost, pred, x, y, lam, alp, n):
  temp_w = copy.deepcopy(w)
  dj_dw = np.zeros(len(w))
  for k in range(len(w)):
    for i in range(number_train):
      dj_dw[k] = (((pred[i] - y[i])/n)*x[i][k]) + ((lam*w[k])/n)
      temp_w[k] = w[k] - (alp * dj_dw[k])
      dj_db = (pred[i] - y[i])/n
      temp_b = b - (alp * dj_db)
    w[k] = temp_w[k]
    b = temp_b
  return w, b
  #print(w_para)
  #print(b_para)

In [383]:
'''def grad_desc(w, b, cost, pred, x, y, lam, alp, n):
      dj_dw = (x.T @ (pred - y)) / n + (lam * w) / n
      dj_db = np.mean(pred - y)
      w = w - (alp * dj_dw)
      b = b - (alp * dj_db)
      return w, b'''

'def grad_desc(w, b, cost, pred, x, y, lam, alp, n):\n      dj_dw = (x.T @ (pred - y)) / n + (lam * w) / n\n      dj_db = np.mean(pred - y) \n      w = w - (alp * dj_dw)\n      b = b - (alp * dj_db)\n      return w, b'

In [384]:
w_para, b_para = grad_desc(w_para, b_para, cost, pred, x_train, y_train, 0.1, 1, number_train)

In [385]:
i = 0
while cost > 0.1:
  pred = predict()
  loss = lossss()
  cost = cost_function(loss, 1, w_para)
  w_para, b_para = grad_desc(w_para, b_para, cost, pred, x_train, y_train, 0.1, 1, number_train)
  print(f'{i}th iteration, {cost}')
  i += 1
else:
  print('done')
  print(w_para)
  print(b_para)
  print(cost)
  print(f'done in {i} iterations')


Streaming output truncated to the last 5000 lines.
5103th iteration, 816.8772037669715
5104th iteration, 816.870287460008
5105th iteration, 816.8633737803191
5106th iteration, 816.8564627250389
5107th iteration, 816.8495542913046
5108th iteration, 816.8426484762563
5109th iteration, 816.8357452770374
5110th iteration, 816.8288446907947
5111th iteration, 816.8219467146772
5112th iteration, 816.815051345839
5113th iteration, 816.808158581435
5114th iteration, 816.8012684186251
5115th iteration, 816.7943808545718
5116th iteration, 816.7874958864405
5117th iteration, 816.7806135113999
5118th iteration, 816.7737337266223
5119th iteration, 816.7668565292824
5120th iteration, 816.7599819165591
5121th iteration, 816.7531098856326
5122th iteration, 816.7462404336885
5123th iteration, 816.7393735579141
5124th iteration, 816.7325092555003
5125th iteration, 816.7256475236408
5126th iteration, 816.718788359533
5127th iteration, 816.7119317603766
5128th iteration, 816.7050777233758
5129th iteration,

KeyboardInterrupt: 