<a href="https://colab.research.google.com/github/CC-Shivansh-Gupta/logistic-_reg/blob/main/v3_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [43]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import copy, math

std_data = pd.read_csv('Student_Performance.csv')
std_data.columns = std_data.columns.str.replace(' ', '_')
std_data
#print(type(std_data))
#print(std_data.info())

Hours_Studied  Previous_Scores Extracurricular_Activities  Sleep_Hours  \
0                 7               99                        Yes            9   
1                 4               82                         No            4   
2                 8               51                        Yes            7   
3                 5               52                        Yes            5   
4                 7               75                         No            8   
...             ...              ...                        ...          ...   
9995              1               49                        Yes            4   
9996              7               64                        Yes            8   
9997              6               83                        Yes            8   
9998              9               97                        Yes            7   
9999              7               74                         No            8   

      Sample_Question_Papers_Practiced  Performance_Index  
0                                    1               91.0  
1                                    2               65.0  
2                                    2               45.0  
3                                    2               36.0  
4                                    5               66.0  
...                                ...                ...  
9995                                 2               23.0  
9996                                 5               58.0  
9997                                 5               74.0  
9998                                 0               95.0  
9999                                 1               64.0  

[10000 rows x 6 columns]

In [44]:
#std_data.rename(columns={'Extracurricular Activities' : 'Extracurricular'}, inplace = True)
#std_data
std_data = std_data.replace('Yes', '1', regex = True)
std_data = std_data.replace('No', '0', regex = True)
std_data['Extracurricular_Activities'] = std_data['Extracurricular_Activities'].astype('int64')
std_data

Hours_Studied  Previous_Scores  Extracurricular_Activities  Sleep_Hours  \
0                 7               99                           1            9   
1                 4               82                           0            4   
2                 8               51                           1            7   
3                 5               52                           1            5   
4                 7               75                           0            8   
...             ...              ...                         ...          ...   
9995              1               49                           1            4   
9996              7               64                           1            8   
9997              6               83                           1            8   
9998              9               97                           1            7   
9999              7               74                           0            8   

      Sample_Question_Papers_Practiced  Performance_Index  
0                                    1               91.0  
1                                    2               65.0  
2                                    2               45.0  
3                                    2               36.0  
4                                    5               66.0  
...                                ...                ...  
9995                                 2               23.0  
9996                                 5               58.0  
9997                                 5               74.0  
9998                                 0               95.0  
9999                                 1               64.0  

[10000 rows x 6 columns]

In [45]:
def normalise_data(arr):
  #min_val = np.min(arr)
  #max_val = np.max(arr)
  mean = np.mean(arr)
  std = np.std(arr)
  norm_arr = np.zeros(len(arr))
  for i in range(len(arr)):
    norm_arr[i] = (arr[i] - mean) / std
  return norm_arr


In [46]:
for i in range(std_data.shape[1]-1):
  std_data.iloc[:, i] = normalise_data(std_data.iloc[:, i])
std_data

<ipython-input-46-fae890c2cb34>:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ 0.77518771 -0.38348058  1.16141048 ...  0.38896495  1.54763324
  0.77518771]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  std_data.iloc[:, i] = normalise_data(std_data.iloc[:, i])
<ipython-input-46-fae890c2cb34>:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ 1.70417565  0.72391268 -1.06362569 ...  0.7815752   1.5888506
  0.26261245]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  std_data.iloc[:, i] = normalise_data(std_data.iloc[:, i])
<ipython-input-46-fae890c2cb34>:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ 1.01045465 -0.98965352  1.01045465 ...  1.01045465  1.01045465
 -0.98965352]' has dtyp

Hours_Studied  Previous_Scores  Extracurricular_Activities  Sleep_Hours  \
0          0.775188         1.704176                    1.010455     1.456205   
1         -0.383481         0.723913                   -0.989654    -1.492294   
2          1.161410        -1.063626                    1.010455     0.276805   
3          0.002742        -1.005963                    1.010455    -0.902594   
4          0.775188         0.320275                   -0.989654     0.866505   
...             ...              ...                         ...          ...   
9995      -1.542149        -1.178951                    1.010455    -1.492294   
9996       0.775188        -0.314013                    1.010455     0.866505   
9997       0.388965         0.781575                    1.010455     0.866505   
9998       1.547633         1.588851                    1.010455     0.276805   
9999       0.775188         0.262612                   -0.989654     0.866505   

      Sample_Question_Papers_Practiced  Performance_Index  
0                            -1.249754               91.0  
1                            -0.900982               65.0  
2                            -0.900982               45.0  
3                            -0.900982               36.0  
4                             0.145333               66.0  
...                                ...                ...  
9995                         -0.900982               23.0  
9996                          0.145333               58.0  
9997                          0.145333               74.0  
9998                         -1.598526               95.0  
9999                         -1.249754               64.0  

[10000 rows x 6 columns]

In [47]:
number = std_data.shape[0]
print(number)
number_train = int(number * 9 / 10)
lam = 0.1
alp = 1

10000


In [48]:
x_train_list = []
for j in range(std_data.shape[1]):
    xj_train = np.zeros(number_train)
    for i in range(number_train):
        xj_train[i] = std_data.iloc[i, j]
    x_train_list.append(xj_train)  # Append xj_train directly to the list

# Separate the features (x_train) from the target (y_train)
x_train_tup = tuple(x_train_list[:-1]) # Exclude the last column (target)
x_train = np.column_stack(x_train_tup)
y_train = x_train_list[-1]  # The last column is the target

print(x_train)
print(y_train)

[[ 0.77518771  1.70417565  1.01045465  1.45620461 -1.24975394]
 [-0.38348058  0.72391268 -0.98965352 -1.49229423 -0.90098215]
 [ 1.16141048 -1.06362569  1.01045465  0.27680507 -0.90098215]
 ...
 [-0.38348058  1.24287543 -0.98965352  0.27680507 -1.24975394]
 [ 1.54763324 -0.71765053 -0.98965352 -0.90259446 -1.59852572]
 [-1.15592611 -0.19868777 -0.98965352 -0.3128947   1.54042034]]
[91. 65. 45. ... 77. 51. 43.]


In [49]:
w_para = np.array([-4.60065594, -0.75392081, -3.94309975, -1.22232583, 6.10488682])
print(w_para)
b_para = 23.647361075152435
print(b_para)

[-4.65295234 -0.76207969 -3.98796864 -1.23596361  6.17399129]
23.427942647094575


In [50]:
def prediction(x, w, b):
  c = np.dot(x, w) + b
  return c

In [51]:
def predict(n, x, w, b):
  predic= np.zeros(n)
  for i in range(n):
    predic[i] = prediction(x[i], w, b)
    #print(predic)
  return predic


In [52]:
pred = predict(number_train, x_train, w_para, b_para)

In [53]:
def loss_calc(p, y):
  loss = 1/2*((p - y) ** 2)
  return loss

In [54]:
def lossss(pr, y, n):
  losses = np.zeros(n)
  for i in range(n):
    losses[i] = loss_calc(pr[i], y[i])
  #print(losses)
  return losses

In [55]:
loss = lossss(pred, y_train, number_train)

In [56]:
def cost_function(losss, l, w):
  costie = np.mean(losss) + (l * np.sum(np.square(w)))/(2*len(losss))
  #print(costie)
  return costie

In [57]:
def rmse(loss):
  rmse = np.sqrt(np.mean(loss))
  return rmse

In [58]:
cost = cost_function(loss, lam, w_para)

In [59]:
def grad_desc(w, b, p, x, y, l, a, n):
  temp_w = copy.deepcopy(w)
  dj_dw = np.zeros(len(w))
  for k in range(len(w)):
    for i in range(n):
      dj_dw[k] = (((p[i] - y[i])/n)*x[i][k]) + ((l*w[k])/n)
      temp_w[k] = w[k] - (a * dj_dw[k])
      dj_db = (p[i] - y[i])/n
      temp_b = b - (a * dj_db)
    w[k] = temp_w[k]
    b = temp_b
  return w, b
  #print(w_para)
  #print(b_para)

In [60]:
'''def grad_desc(w, b, cost, pred, x, y, lam, alp, n):
      dj_dw = (x.T @ (pred - y)) / n + (lam * w) / n
      dj_db = np.mean(pred - y)
      w = w - (alp * dj_dw)
      b = b - (alp * dj_db)
      return w, b'''

'def grad_desc(w, b, cost, pred, x, y, lam, alp, n):\n      dj_dw = (x.T @ (pred - y)) / n + (lam * w) / n\n      dj_db = np.mean(pred - y)\n      w = w - (alp * dj_dw)\n      b = b - (alp * dj_db)\n      return w, b'

In [61]:
w_para, b_para = grad_desc(w_para, b_para, pred, x_train, y_train, lam, alp, number_train)
i = 0

In [67]:

#iter = np.empty(1001)
#w_1 = np.empty(1001)
cost_change = 1
while abs(cost_change) > 0.001 or i < 1000:
  pred = predict(number_train, x_train, w_para, b_para)
  loss = lossss(pred, y_train, number_train)
  temp_cost = cost_function(loss, lam, w_para)
  cost_change = abs(temp_cost - cost)
  cost = temp_cost
  w_para, b_para = grad_desc(w_para, b_para, pred, x_train, y_train, lam, alp, number_train)
  print(f'{i}th iteration, {cost}')
  #w_1[i] = w_para[0]
  #iter[i] = i
  #plt.plot(iter, w_1)
  #plt.show()
  i += 1
else:
  print('done')
  print(w_para)
  print(b_para)
  print(cost)
  print(f'done in {i} iterations')


999th iteration, 761.1840124906248
1000th iteration, 761.1799270767102
1001th iteration, 761.1758416999396
1002th iteration, 761.1717563603136
1003th iteration, 761.1676710578307
1004th iteration, 761.1635857924921
1005th iteration, 761.1595005642964
1006th iteration, 761.1554153732429
1007th iteration, 761.151330219332
1008th iteration, 761.1472451025627
1009th iteration, 761.1431600229349
1010th iteration, 761.1390749804482
1011th iteration, 761.1349899751026
1012th iteration, 761.1309050068975
1013th iteration, 761.1268200758324
1014th iteration, 761.1227351819069
1015th iteration, 761.1186503251206
1016th iteration, 761.1145655054735
1017th iteration, 761.1104807229647
1018th iteration, 761.1063959775939
1019th iteration, 761.1023112693614
1020th iteration, 761.0982265982658
1021th iteration, 761.0941419643074
1022th iteration, 761.090057367486
1023th iteration, 761.0859728078009
1024th iteration, 761.0818882852516
1025th iteration, 761.0778037998379
1026th iteration, 761.073719351

KeyboardInterrupt: 

In [64]:
print(w_para)
print(b_para)

[-4.60065594 -0.75392081 -3.94309975 -1.22232583  6.10488682]
23.647361075152435


In [65]:
number_test = number - number_train
print(number_test)
x_test_list = []
for j in range(std_data.shape[1]):
    xj_test = np.zeros(number_test)
    for i in range(number_test):
        xj_test[i] = std_data.iloc[i + number_train, j]
    x_test_list.append(xj_test)  # Append xj_train directly to the list

# Separate the features (x_train) from the target (y_train)
x_test_tup = tuple(x_test_list[:-1]) # Exclude the last column (target)
x_test = np.column_stack(x_test_tup)
y_test = x_test_list[-1]  # The last column is the target

print(x_test)
#print(y_test)

1000
[[-1.54214888 -0.71765053  1.01045465  0.86650484 -1.59852572]
 [ 1.16141048  0.08962487 -0.98965352  1.45620461  0.1453332 ]
 [ 1.54763324  1.5888506   1.01045465  1.45620461 -1.24975394]
 ...
 [ 0.38896495  0.7815752   1.01045465  0.86650484  0.1453332 ]
 [ 1.54763324  1.5888506   1.01045465  0.27680507 -1.59852572]
 [ 0.77518771  0.26261245 -0.98965352  0.86650484 -1.24975394]]


In [66]:
test_pred = predict(number_test, x_test, w_para, b_para)
test_loss = lossss(test_pred, y_test, number_test)
test_cost = cost_function(test_loss, lam, w_para)
print(test_cost)
test_rmse = rmse(test_loss)
print(test_rmse)

793.4967248597471
28.169006417518577
